name: build-changelog
on: 
  workflow_dispatch
permissions: {}
jobs:
  build-changelog:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@547101fba00529da047dc80c78f97ef658ec89b2 # v4
