name: build-changelog
on: 
  workflow_dispatch
permissions: {}
jobs:
  build-changelog:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@c73ff7421c59fa0d090dcfe62e24a758977c699d # v4
